version: '3'

services:
    web:
        build: ./web
        ports:
            -   9100:8080
        environment: 
            DATABASE_NAME:  demo
            DATABASE_USER:  demo
            DATABASE_PASS:  demo
            DATABASE_URL:   jdbc:mysql://demo:demo@db:3306/demo    
        volumes: 
            -   /usr/local/tomcat/webapps
            -   /usr/local/tomcat/logs

            db:
        build: ./db
        ports:
            -   3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD:    password
            MYSQL_DATABASE: demo
            MYSQL_USER: demo
            MYSQL_PASSWORD: demo
        command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        volumes: 
            -   /var/lib/mysql
            -   /var/log/mysql

    adminer:
        build: ./adminer
        ports:
            -   9101:8080

